---
# Source: mayastor-control-plane/templates/core-agents-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-agents
  namespace: mayastor
  labels:
    app: core-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-agents
  template:
    metadata:
      labels:
        app: core-agents
    spec:
      initContainers:
        - command:
          - sh
          - -c
          - trap "exit 1" TERM; until nc -vz nats 4222; do echo "Waiting for nats..."; sleep
            1; done;
          image: busybox:latest
          name: nats-probe
        - command:
          - sh
          - -c
          - trap "exit 1" TERM; until nc -vz mayastor-etcd-client 2379; do echo "Waiting for etcd...";
            sleep 1; done;
          image: busybox:latest
          name: etcd-probe
      containers:
        - name: core
          resources:
            limits:
              cpu: 1000m
              memory: 32Mi
            requests:
              cpu: 500m
              memory: 16Mi
          image: mayadata/mcp-core:v1.0.1
          imagePullPolicy: IfNotPresent
          args:
            - "-smayastor-etcd-client"
            - "-nnats"
            - "--request-timeout=5s"
            - "--cache-period=30s"
          env:
            - name: RUST_LOG
              value: info
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
